// app/[locale]/layout.jsx

import { notFound } from "next/navigation";
import { getMessages, setRequestLocale } from "next-intl/server";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "../globals.css";

import NavBar from "@/components/layout/NavBar";
import NavbarMobile from "@/components/layout/NavbarMobile";
import Footer from "@/components/layout/Footer";
import ReactQueryProvider from "@/lib/ReactQueryProvider";
import LocaleQueryInvalidator from "@/components/layout/LocaleQueryInvalidator";
import { Suspense } from "react";
import SplashScreen from "@/components/splashScreen/SplashScreen";
import AuthModals from "@/components/auth/AuthModals";
import { Toaster } from "react-hot-toast";

// --- إعداد الخطوط (Fonts) ---
const lufga = localFont({
  src: [
    {
      path: "../../../public/fonts/lufga/LufgaThin.woff",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../../public/fonts/lufga/LufgaLight.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../../public/fonts/lufga/LufgaRegular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/lufga/LufgaSemiBold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../../public/fonts/lufga/LufgaBold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-lufga",
});

const ping = localFont({
  src: [
    {
      path: "../../../public/fonts/ping-ar/alfont_com_PingARLT-Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../../public/fonts/ping-ar/alfont_com_PingARLT-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../../public/fonts/ping-ar/alfont_com_PingARLT-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/ping-ar/alfont_com_PingARLT-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-ping-ar",
});

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });

// --- الميتاداتا (Metadata) ---
export const metadata = {
  title: "Velvet",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params }) {
  const { locale } = await params; // في Next 15 الـ params هي Promise
  setRequestLocale(locale);

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const fontClass = locale === "ar" ? ping.className : lufga.className;
  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body
        className={`${fontClass} ${lufga.variable} ${ping.variable} ${geistSans.variable} antialiased`}
      >
        <SplashScreen />
        <ReactQueryProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <LocaleQueryInvalidator />

            {/* التنقل (Navigation) */}

            {/* <div className="lg:block hidden"> */}
            <Suspense>
              <NavBar />
            </Suspense>
            {/* </div> */}
            <div className="lg:hidden block">
              <Suspense>
                <NavbarMobile />
              </Suspense>
            </div>

            <Toaster
              position="top-center"
              toastOptions={{
                style: { marginTop: "5rem" },
                duration: 3000,
              }}
            />

            <main>{children}</main>

            <AuthModals />
            <Footer />
          </NextIntlClientProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
