// app/[locale]/layout.jsx

import { notFound } from "next/navigation";
import { getMessages, setRequestLocale } from "next-intl/server";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { Geist } from "next/font/google";
import localFont from "next/font/local";
import "../globals.css";

import NavBar from "@/components/layout/NavBar";
import NavbarMobile from "@/components/layout/NavbarMobile";
import Footer from "@/components/layout/Footer";
import ReactQueryProvider from "@/lib/ReactQueryProvider";
import LocaleQueryInvalidator from "@/components/layout/LocaleQueryInvalidator";
import { Suspense } from "react";
import SplashScreen from "@/components/splashScreen/SplashScreen";
import AuthModals from "@/components/auth/AuthModals";
import NotificationsProvider from "@/components/notifications/NotificationsProvider";
import { Toaster } from "react-hot-toast";

// --- Fonts Setup ---
const lufga = localFont({
  src: [
    {
      path: "../../../public/fonts/lufga/LufgaThin.woff",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../../public/fonts/lufga/LufgaLight.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../../public/fonts/lufga/LufgaRegular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/lufga/LufgaSemiBold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../../public/fonts/lufga/LufgaBold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-lufga",
});

const ping = localFont({
  src: [
    {
      path: "../../../public/fonts/ping-ar/alfont_com_PingARLT-Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../../public/fonts/ping-ar/alfont_com_PingARLT-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../../public/fonts/ping-ar/alfont_com_PingARLT-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/ping-ar/alfont_com_PingARLT-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-ping-ar",
});

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });

export const metadata = {
  title: "Velvet",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  setRequestLocale(locale);

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const fontClass = locale === "ar" ? ping.className : lufga.className;
  const messages = await getMessages();

  // suppressHydrationWarning on <html>: the inline splash script below adds
  // the "show-splash" class to <html> in the browser before React hydrates,
  // so the DOM intentionally differs from the server HTML.
  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"} suppressHydrationWarning>
      <head>
        {/* CSS rule applied IMMEDIATELY on first byte parsed */}
        <style
          dangerouslySetInnerHTML={{
            __html: `
              html.show-splash body > *:not(#instant-splash-screen) {
                visibility: hidden !important;
              }
            `,
          }}
        />
        {/* Instant blocking script before body starts */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  if (!sessionStorage.getItem('hasSeenSplash')) {
                    document.documentElement.classList.add('show-splash');
                  }
                } catch(e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${fontClass} ${lufga.variable} ${ping.variable} ${geistSans.variable} antialiased`}
      >
        <SplashScreen />

        <ReactQueryProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <LocaleQueryInvalidator />

            <Suspense fallback={<div className="h-20 w-full" />}>
              <NavBar />
            </Suspense>

            <div className="lg:hidden block">
              <Suspense fallback={<div className="h-16 w-full" />}>
                <NavbarMobile />
              </Suspense>
            </div>

            <Toaster
              position="top-center"
              toastOptions={{
                style: { marginTop: "5rem" },
                duration: 3000,
              }}
            />

            {/* FCM root provider — registers the SW + token, listens for messages */}
            <NotificationsProvider>
              <main>{children}</main>
              <AuthModals />
              <Footer />
            </NotificationsProvider>
          </NextIntlClientProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
} 